from typing import Any, Literal
from pydantic import BaseModel, Field

from schemas.mission import MissionNode
from schemas.timeline import TimeBlock
from schemas.memory import MemoryItem
from schemas.dashboard import AIRecommendation, RiskAssessment
from schemas.agent import AgentActivity


class Mutation(BaseModel):
    """Represents a deferred write operation for Firestore."""
    operation: Literal["create", "update", "delete"]
    collection: str
    doc_id: str
    data: dict[str, Any] | None = None


class PipelineContext(BaseModel):
    """In-memory state maintained throughout the duration of a single agent pipeline execution."""
    
    # -------------------------------------------------------------------------
    # Loaded State (Read-Only references or mutable in-memory copies)
    # -------------------------------------------------------------------------
    
    # The primary mission being orchestrated
    mission: MissionNode
    
    # All missions for dependency mapping and context
    all_missions: list[MissionNode] = Field(default_factory=list)
    
    # Timeline blocks
    timeline: list[TimeBlock] = Field(default_factory=list)
    
    # Calendar events
    calendar_events: list[Any] = Field(default_factory=list)
    
    # User Profile (including settings and dynamic_model)
    user_profile: Any = None
    
    # Recent Memories
    memories: list[MemoryItem] = Field(default_factory=list)
    
    # Active Recommendations
    recommendations: list[AIRecommendation] = Field(default_factory=list)

    # Mission Success
    mission_success: Any = None
    
    # -------------------------------------------------------------------------
    # Mutated State (Generated during pipeline execution)
    # -------------------------------------------------------------------------
    
    # Activities generated by agents (operational logs)
    activities: list[AgentActivity] = Field(default_factory=list)
    
    # Reflections generated by agents
    reflections: list[str] = Field(default_factory=list)
    
    # Risk Assessment generated by the Risk Agent
    risk_assessment: RiskAssessment | None = None
    
    # Deferred mutations to be committed in one batch at the end
    mutations: list[Mutation] = Field(default_factory=list)

    def add_mutation(self, operation: Literal["create", "update", "delete"], collection: str, doc_id: str, data: dict[str, Any] | None = None) -> None:
        """Helper to append a mutation."""
        self.mutations.append(Mutation(
            operation=operation,
            collection=collection,
            doc_id=doc_id,
            data=data
        ))
